In [1]:
import os
import numpy as np
import board
import pickle
import board as Board
import player
import game
from copy import deepcopy
from mcts import *

from neural_network import*

Using TensorFlow backend.


In [2]:
player1 = player.Zero_Player('x', 'Bot_ZERO', nn_type="w", temperature=1)
player2 = player.Zero_Player('o', 'Bot_ZERO', nn_type="w", temperature=1)

In [3]:
brd = b.Board()
tree = MCTS()
PATH = {"path":[]}


In [5]:
players = [player1, player2]
test = np.array([[  1,   -1,  1],
                 [  0,   1,   0],
                 [  0,   0,  -1]])
turn = 5
n_map = {-1:"o", 0: " ", 1: "x"}

str_state = ''.join([n_map[i] for i in test.reshape(9,)])
str_state

brd.board = test

simulate(players, turn, brd, tree.TREE, PATH, root = brd, n = 10)

tree.update_nodes()

In [6]:
root = [x for x in tree.TREE.values() if x.is_root()][0]

for x in [root]:
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.Q)

[[ 1 -1  1]
 [ 0  1  0]
 [ 0  0 -1]]
xox x   o
[]
W: 10 L 2 D 8
N: 20
Q 0.7


In [7]:
for x in tree.TREE.values():
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.Q)


[[ 1 -1  1]
 [ 0  1  0]
 [ 0  0 -1]]
xox x   o
[]
W: 10 L 2 D 8
N: 20
Q 0.7
[[ 1 -1  1]
 [ 0  1 -1]
 [ 0  0 -1]]
xox xo  o
[]
W: 2 L 0 D 4
N: 6
Q 0.6666666666666666
[[ 1 -1  1]
 [ 0  1 -1]
 [ 1  0 -1]]
xox xox o
[]
W: 2 L 0 D 0
N: 2
Q 1.0
[[ 1 -1  1]
 [ 0  1  0]
 [-1  0 -1]]
xox x o o
[]
W: 0 L 1 D 3
N: 4
Q 0.375
[[ 1 -1  1]
 [ 0  1  0]
 [-1  1 -1]]
xox x oxo
[]
W: 0 L 0 D 1
N: 1
Q 0.5
[[ 1 -1  1]
 [ 0  1 -1]
 [-1  1 -1]]
xox xooxo
[]
W: 0 L 0 D 3
N: 3
Q 0.5
[[ 1 -1  1]
 [ 1  1 -1]
 [-1  1 -1]]
xoxxxooxo
[]
W: 0 L 0 D 6
N: 6
Q 0.5
[[ 1 -1  1]
 [-1  1  0]
 [ 0  0 -1]]
xoxox   o
[]
W: 4 L 0 D 1
N: 5
Q 0.9
[[ 1 -1  1]
 [-1  1  0]
 [ 0  1 -1]]
xoxox  xo
[]
W: 1 L 0 D 1
N: 2
Q 0.75
[[ 1 -1  1]
 [-1  1  0]
 [-1  1 -1]]
xoxox oxo
[]
W: 0 L 0 D 1
N: 1
Q 0.5
[[ 1 -1  1]
 [-1  1  1]
 [-1  1 -1]]
xoxoxxoxo
[]
W: 0 L 0 D 2
N: 2
Q 0.5
[[ 1 -1  1]
 [-1  1  1]
 [ 0  0 -1]]
xoxoxx  o
[]
W: 2 L 0 D 0
N: 2
Q 1.0
[[ 1 -1  1]
 [-1  1  1]
 [ 0 -1 -1]]
xoxoxx oo
[]
W: 2 L 0 D 0
N: 2
Q 1.0
[[ 1 -1  1]
 [-1  

In [ ]:
for x in root.children:
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.Q)

In [ ]:
terminal = [x for x in TREE.values() if x.is_leaf()]

for x in terminal:
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.value)

In [ ]:
bod = b.Board()
TREE = {}
EDGES = {}

test = np.array([[  1,   -1,  1],
                 [  0,   1,   -1],
                 [  0,   0,  -1]])

n_map = {-1:"o", 0: " ", 1: "x"}

str_state = ''.join([n_map[i] for i in test.reshape(9,)])
str_state

bod.board = test

players = [player1, player2]
turn = 6

simulate(players, bod, TREE, EDGES, turn)

In [ ]:
term_Edge = [x for x in EDGES.values() if x.terminal]
term_Edge

In [ ]:
EDGES

In [ ]:
for edge in term_Edge:
    parent_edges = [e for e in EDGES if e.to_node = edge.from]
    for [p in parent_edges]:
        p.W = sum([node.W for node in parent.children])
        p.L = sum([node.L for node in parent.children])
        p.D = sum([node.D for node in parent.children])
    

In [ ]:
for x in term_Edge:
    
    print(x.from_node, x.to_node)
    print(x.N)
    print("W:",x.W, "L",x.L, "D", x.D)

In [ ]:
root = [x for x in TREE.values() if x.is_root()][0]
root
root.N_eval

In [ ]:
for x in [root]:
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.value)

In [ ]:
def eval_to_leaf(parent):
    parent.N = sum([edge.N for edge in parent.edges])
    while parent.value_eval == False:
        middle = [node for node in parent.children if not node.value_eval]
        for mid_node in middle:
            eval_value_to_leaf(mid_node)
        
        all_eval = len(middle)==0
        if all_eval:
            if not parent.is_leaf():
                parent.W = sum([node.W for node in parent.children])
                parent.L = sum([node.L for node in parent.children])
                parent.D = sum([node.D for node in parent.children])

            parent.value_eval = True

    
eval_value_to_leaf(root)

In [ ]:
def 

In [ ]:
for x in root.edges:
    print(x.from_node, x.to_node)
    print(x.N)
    print("W:",x.W, "L",x.L, "D", x.D)


In [ ]:
for x in EDGES.values():
    print(x.from_node, " to ",x.to_node)
    print(x.N)
    print("W:",x.W, "L",x.L, "D", x.D)


In [ ]:
terminal = [x for x in TREE.values() if x.is_leaf()]
terminal

In [ ]:
leaf = terminal[0]
leaf.parent
print(leaf.board_arr)
[edge for parent in leaf.parent for edge in parent.edges if edge.to_node == leaf.id]

In [ ]:
def eval_to_leaf(node):

In [ ]:
terminal = [x for x in TREE.values() if x.is_leaf()]
for leaf in TREE.values():
    parents = leaf.parent
    all_paths = [edge for parent in leaf.parent for edge in parent.edges if edge.to_node == leaf.id]
    unique_paths = list(set(all_paths))
    
    leaf.N = sum([edge.N for edge in unique_paths])
    leaf.W = sum([edge.W for edge in unique_paths])
    leaf.L = sum([edge.L for edge in unique_paths])
    leaf.D = sum([edge.D for edge in unique_paths])


In [ ]:
for x in TREE.values():
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.value)

In [ ]:
terminal = [x for x in TREE.values() if x.is_leaf()]
for x in terminal:
    print(x)
    print (x.board_arr)
    print(x.id)
    print(x.turn)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.value)

In [ ]:
Board.str2arr("xoxxxooxo")

In [ ]:
bod = b.Board()
TREE = {}

test = np.array([[  0,   0,  0],
                 [  0,  0,  0],
                 [  0,   0,  0]])

n_map = {-1:"o", 0: " ", 1: "x"}

str_state = ''.join([n_map[i] for i in test.reshape(9,)])
str_state

bod.board = test

players = [player1, player2]
turn = 0

simulate(players, bod, nodes, edge_statistics, turn)

In [ ]:
value_df = create_values_df(nodes)
moves_df = create_policy_df(edge_statistics)

In [ ]:
def check_rot_inv(new_node_id, node_id_list):
    sym = [new_node_id]
    board_arr = bod.str2arr(new_node_id)
    
    for i in range(1,4):
        rot = np.rot90(board_arr, k=i)
        sym.append(bod.str2arr())

In [ ]:
value_dfboard 

In [ ]:
test = np.array([[ 1,  0,  0],
                 [ 0,  0, 0],
                 [ 0,  0, 0]])

np.flip(test)

In [ ]:
node_tree_dict = {}

for idx, value in moves_df.iterrows():
    parent_id = value["init_state"]
    child_id = value["final_state"]
    
    if not parent_id in node_tree_dict.keys():
        parent_node = Node(parent_id)
        node_tree_dict[parent_id] = parent_node
    else:
        parent_node = node_tree_dict[parent_id]
        
    if not child_id in node_tree_dict.keys():
        child_node = Node(child_id)
        node_tree_dict[child_id] = child_node
    else:
        child_node = node_tree_dict[child_id]
        
    parent_node.children.append(child_node)
    child_node.parent.append(parent_node)
    
terminal = [x for x in node_tree_dict.values() if x.is_leaf()]
for node in terminal:
    board_arr = bod.str2arr(node.id)
    node.board_arr = board_arr
    winner = b.Board.winner(board_arr)
    node.value = winner
    node.N+=1
    node.eval = True

root = [x for x in node_tree_dict.values() if x.is_root()][0]
root
parent = root

In [ ]:
eval_to_leaf(root)


In [ ]:
for x in [root]:
    print (x.board_arr)
    print(x.id)
    print(x.turn)
    print(x.N)
    print("Q",x.value)

In [ ]:
X = [x.id for x in node_tree_dict.values()]
Y = [x.value for x in node_tree_dict.values()]

In [ ]:
data = pd.DataFrame({
    'init_state': X,
    'Value': Y,
    })

data.sort_values("init_state")

In [ ]:
data.to_csv("training_data.csv", index=False)