In [1]:
import os
import numpy as np
import board
import pickle
import board as Board
import player
import game
from copy import deepcopy
from mcts import *

from neural_network import*

Using TensorFlow backend.


In [9]:
import sys

sys.path

['/Users/yidinghou/Desktop/Projects/tic-tac-GO_zero',
 '/Users/yidinghou/anaconda3/lib/python37.zip',
 '/Users/yidinghou/anaconda3/lib/python3.7',
 '/Users/yidinghou/anaconda3/lib/python3.7/lib-dynload',
 '',
 '/Users/yidinghou/.local/lib/python3.7/site-packages',
 '/Users/yidinghou/anaconda3/lib/python3.7/site-packages',
 '/Users/yidinghou/anaconda3/lib/python3.7/site-packages/aeosa',
 '/Users/yidinghou/anaconda3/lib/python3.7/site-packages/object_detection-0.1-py3.7.egg',
 '/Users/yidinghou/anaconda3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/yidinghou/.ipython']

In [2]:
player1 = player.Zero_Player('x', 'Bot_ZERO', nn_type="w", temperature=1)
player2 = player.Zero_Player('o', 'Bot_ZERO', nn_type="w", temperature=1)

In [3]:
brd = b.Board()
tree = MCTS()
PATH = {"path":[]}


In [4]:
players = [player1, player2]
test = np.array([[  1,   -1,  1],
                 [  0,   1,   0],
                 [  0,   0,  -1]])
turn = 5
n_map = {-1:"o", 0: " ", 1: "x"}

str_state = ''.join([n_map[i] for i in test.reshape(9,)])
str_state

brd.board = test

simulate(players, turn, brd, tree.TREE, PATH, root = brd, n = 10)

tree.update_nodes()

In [5]:
root = [x for x in tree.TREE.values() if x.is_root()][0]

for x in [root]:
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.Q)

[[ 1 -1  1]
 [ 0  1  0]
 [ 0  0 -1]]
xox x   o
[]
W: 5 L 1 D 4
N: 10
Q 0.7


In [6]:
for x in tree.TREE.values():
    print(x)
    print(x.board_arr)
    print(x.id)
    print(x.edges)
    print("W:",x.W, "L",x.L, "D", x.D)
    print("N:", x.N)
    print("Q",x.Q)


[[ 1 -1  1]
 [ 0  1  0]
 [ 0  0 -1]]
xox x   o
[]
W: 5 L 1 D 4
N: 10
Q 0.7
[[ 1 -1  1]
 [ 0  1  0]
 [ 0 -1 -1]]
xox x  oo
[]
W: 2 L 1 D 0
N: 3
Q 0.6666666666666666
[[ 1 -1  1]
 [ 0  1  0]
 [ 1 -1 -1]]
xox x xoo
[]
W: 2 L 0 D 0
N: 2
Q 1.0
[[ 1 -1  1]
 [-1  1  0]
 [ 0  0 -1]]
xoxox   o
[]
W: 0 L 0 D 1
N: 1
Q 0.5
[[ 1 -1  1]
 [-1  1  0]
 [ 0  1 -1]]
xoxox  xo
[]
W: 0 L 0 D 1
N: 1
Q 0.5
[[ 1 -1  1]
 [-1  1  0]
 [-1  1 -1]]
xoxox oxo
[]
W: 0 L 0 D 3
N: 3
Q 0.5
[[ 1 -1  1]
 [-1  1  1]
 [-1  1 -1]]
xoxoxxoxo
[]
W: 0 L 0 D 3
N: 3
Q 0.5
[[ 1 -1  1]
 [ 0  1  0]
 [-1  0 -1]]
xox x o o
[]
W: 0 L 0 D 2
N: 2
Q 0.5
[[ 1 -1  1]
 [ 0  1  0]
 [-1  1 -1]]
xox x oxo
[]
W: 0 L 0 D 2
N: 2
Q 0.5
[[ 1 -1  1]
 [ 1  1  0]
 [ 0 -1 -1]]
xoxxx  oo
[]
W: 0 L 1 D 0
N: 1
Q 0.0
[[ 1 -1  1]
 [ 1  1  0]
 [-1 -1 -1]]
xoxxx ooo
[]
W: 0 L 1 D 0
N: 1
Q 0.0
[[ 1 -1  1]
 [ 0  1 -1]
 [ 0  0 -1]]
xox xo  o
[]
W: 3 L 0 D 1
N: 4
Q 0.875
[[ 1 -1  1]
 [ 1  1 -1]
 [ 0  0 -1]]
xoxxxo  o
[]
W: 2 L 0 D 0
N: 2
Q 1.0
[[ 1 -1  1]
 [ 1  1 

In [7]:
tree.TREE

{'xox x   o': <mcts.Node at 0x7fa7a4a8ebe0>,
 'xox x  oo': <mcts.Node at 0x7fa79cf18c88>,
 'xox x xoo': <mcts.Node at 0x7fa79cf18be0>,
 'xoxox   o': <mcts.Node at 0x7fa7a4a76518>,
 'xoxox  xo': <mcts.Node at 0x7fa79cf18b00>,
 'xoxox oxo': <mcts.Node at 0x7fa79cf18ac8>,
 'xoxoxxoxo': <mcts.Node at 0x7fa79cf18748>,
 'xox x o o': <mcts.Node at 0x7fa79cf18b70>,
 'xox x oxo': <mcts.Node at 0x7fa79cf187b8>,
 'xoxxx  oo': <mcts.Node at 0x7fa7a4a8ec50>,
 'xoxxx ooo': <mcts.Node at 0x7fa7a4a8ed68>,
 'xox xo  o': <mcts.Node at 0x7fa79cf18710>,
 'xoxxxo  o': <mcts.Node at 0x7fa7a4a8ee10>,
 'xoxxxo oo': <mcts.Node at 0x7fa7a4a8eeb8>,
 'xoxxxoxoo': <mcts.Node at 0x7fa7a4a8ef60>,
 'xox xox o': <mcts.Node at 0x7fa7a4a8a128>,
 'xox xo xo': <mcts.Node at 0x7fa7a4a8a2b0>,
 'xox xooxo': <mcts.Node at 0x7fa7a4a8a358>,
 'xoxxxooxo': <mcts.Node at 0x7fa7a4a8a400>}

In [8]:
player2.tree = tree.TREE
player2.turn(brd)

AttributeError: 'Zero_Player' object has no attribute 'keras_nn'